import { PHOTO_FALLBACK_ATTR } from "../utils/PlayerPhoto.js";

const formatMillions = (value) => {
  const millions = (Number(value) || 0) / 1000000;
  return Number.isInteger(millions) ? String(millions) : millions.toFixed(1);
};
const formatInput = (value) => formatMillions(value).replace(",", ".");
const statusLabel = (status) => status === "OSA" ? "ОСА" : status === "NSA" ? "НСА" : status;
const normalizeStats = (stats = {}) => ({ games: Number(stats.games) || 0, goals: Number(stats.goals) || 0, assists: Number(stats.assists) || 0, points: Number(stats.points) || (Number(stats.goals) || 0) + (Number(stats.assists) || 0), penaltyMinutes: Number(stats.penaltyMinutes) || 0, shotsAgainst: Number(stats.shotsAgainst) || 0, saves: Number(stats.saves) || 0, goalsAgainst: Number(stats.goalsAgainst) || 0, savePercentage: Number(stats.savePercentage) || 0 });
const formatPpg = (stats = {}) => { const row = normalizeStats(stats); return row.games ? (row.points / row.games).toFixed(2) : "0.00"; };
const isGoalieRow = (row) => row?.position === "\u0412\u0420\u0422";
const formatSavePercentage = (value) => { const safe = Number(value) || 0; return safe ? safe.toFixed(3).replace(/^0/, "") : "-"; };
const formatSeasonStatsLine = (row) => {
  const stats = normalizeStats(row.seasonStats);
  if (isGoalieRow(row)) return `\u0418 ${stats.games} \u2022 SV% ${formatSavePercentage(stats.savePercentage)} \u2022 SV ${stats.saves} \u2022 GA ${stats.goalsAgainst}`;
  return `\u0418 ${stats.games} \u2022 ${stats.goals}+${stats.assists}=${stats.points} \u2022 ${formatPpg(stats)} \u041e/\u0418`;
};
const isOsa = (row) => row?.ufaStatus === "OSA" || row?.ufaStatus === "ОСА";
const renderReason = (reason) => `<div class="season-contract-reason ${reason.value >= 0 ? "pos" : "neg"}">${reason.value >= 0 ? "+" : ""}${reason.value} ${reason.text}</div>`;
const renderBadge = (row, decision) => {
  if (decision === "external-offer") return `<span class="season-contract-badge good">Оффер</span>`;
  if (decision === "qualified") return `<span class="season-contract-badge good">QO</span>`;
  if (row.isRenewalLocked) return `<span class="season-contract-badge danger">НХЛ / АХЛ</span>`;
  if (row.hasFutureContract) return `<span class="season-contract-badge good">Продлен</span>`;
  if (decision === "release") return `<span class="season-contract-badge danger">Отпустить</span>`;
  return `<span class="season-contract-badge pending">Без решения</span>`;
};
const renderCapSummary = (salaryCap) => {
  if (!salaryCap?.enabled) return "";
  const remainingClass = Number(salaryCap.remainingRub) <= 0 ? " danger" : "";
  return `<div class="season-contract-cap-summary${remainingClass}"><div><span>Следующий сезон</span><strong>${salaryCap.seasonLabel}</strong></div><div><span>Потолок</span><strong>${formatMillions(salaryCap.capRub)} млн</strong></div><div><span>Занято</span><strong>${formatMillions(salaryCap.payrollRub)} млн</strong></div><div><span>Можно потратить</span><strong>${formatMillions(salaryCap.remainingRub)} млн</strong></div></div>`;
};
const getDecision = (row, view) => view.externalOfferPlayerIds?.has?.(row.playerId) ? "external-offer" : view.qualifiedPlayerIds?.has?.(row.playerId) ? "qualified" : view.releasePlayerIds.has(row.playerId) ? "release" : row.hasFutureContract ? "renewed" : "pending";
const renderOfferControls = (row, offer) => `<div class="season-contract-offer"><div class="season-contract-years">${[1, 2, 3, 4].map((years) => `<button class="season-contract-chip${offer.years === years ? " active" : ""}" data-action="season-contract-years" data-player-id="${row.playerId}" data-years="${years}">${years} г.</button>`).join("")}</div><div class="season-contract-salary"><button class="season-contract-step" data-action="season-contract-adjust-salary" data-player-id="${row.playerId}" data-delta-million="-5">-5</button><button class="season-contract-step" data-action="season-contract-adjust-salary" data-player-id="${row.playerId}" data-delta-million="-1">-1</button><input class="season-contract-input" type="number" min="0.5" step="0.5" value="${formatInput(offer.salaryRub)}" data-action="season-contract-salary-input" data-player-id="${row.playerId}"><span>млн</span><button class="season-contract-step" data-action="season-contract-adjust-salary" data-player-id="${row.playerId}" data-delta-million="1">+1</button><button class="season-contract-step" data-action="season-contract-adjust-salary" data-player-id="${row.playerId}" data-delta-million="5">+5</button><button class="season-contract-step wide" data-action="season-contract-market-salary" data-player-id="${row.playerId}">Рынок</button><button class="season-contract-step wide" data-action="season-contract-demand-salary" data-player-id="${row.playerId}">Ожидание</button></div></div>`;
const renderRow = (row, view) => { const decision = getDecision(row, view); const rowKey = row.rowKey || row.playerId; return `<button class="season-contract-player${view.selectedRowKey === rowKey ? " active" : ""}" data-action="season-contract-select" data-player-id="${row.playerId}" data-row-key="${rowKey}"><img src="${row.photoUrl}" alt="${row.displayName}" ${PHOTO_FALLBACK_ATTR}><span class="season-contract-player-main"><strong>${row.displayName}</strong><small>${row.position} • ${row.age} лет • OVR ${row.ovr}</small><small class="season-contract-player-stats">${formatSeasonStatsLine(row)}</small></span>${renderBadge(row, decision)}</button>`; };
export class SeasonContractDecisionRenderer {
  render(view) {
    if (!view?.isOpen) return "";
    const rows = view.filteredRows || [], selected = view.selectedRow || rows[0] || null, decision = selected ? getDecision(selected, view) : "pending";
    const filters = [["all", "Все"], ["pending", "Без решения"], ["osa", "ОСА"], ["nsa", "НСА"], ["external", "НХЛ / АХЛ"], ["renewed", "Продлены"], ["release", "Отпустить"]];
    const filterMarkup = filters.map(([id, label]) => `<button class="season-contract-filter${view.filter === id ? " active" : ""}" data-action="season-contract-filter" data-filter="${id}">${label}</button>`).join("");
    const preview = selected?.preview || null, offer = view.offersByPlayerId[selected?.playerId] || preview?.offer || null, chance = Math.max(0, Math.min(100, Number(preview?.state?.chance) || 0));
    const headerText = view.osaCount ? "Продлите игроков, квалифицируйте ОСА для сохранения прав или отпустите их на рынок." : "Продлите игроков или отпустите их на рынок свободных агентов.";
    const detail = selected ? `<section class="season-contract-detail"><div class="season-contract-detail-head"><img src="${selected.photoUrl}" alt="${selected.displayName}" ${PHOTO_FALLBACK_ATTR}><div><div class="season-contract-kicker">${statusLabel(selected.ufaStatus)} • ${selected.location === "junior" ? "молодежка" : "основа"}</div><h3>${selected.displayName}</h3><p>${selected.position} • ${selected.age} лет • OVR ${selected.ovr} • ${selected.contractType}</p></div>${renderBadge(selected, decision)}</div><div class="season-contract-detail-grid"><div><span>Текущая зарплата</span><strong>${formatMillions(selected.salaryRub)} млн</strong></div><div><span>Контракт до</span><strong>${selected.contractEndDate || "31.05"}</strong></div><div><span>Статус</span><strong>${statusLabel(selected.ufaStatus)}</strong></div><div><span>Матчи КХЛ</span><strong>${selected.khlGamesPlayed}</strong></div></div>${preview ? `<div class="season-contract-market"><div><span>Рынок</span><strong>${formatMillions(preview.marketSalary)} млн</strong></div><div><span>Ожидание от клуба</span><strong>${formatMillions(preview.teamAdjustedDemand)} млн</strong></div><div><span>Шанс согласия</span><strong>${preview.state.emoji} ${preview.state.chance}%</strong></div></div><div class="season-contract-chance"><span style="width:${chance}%"></span></div><div class="season-contract-reasons">${(preview.reasons || []).slice(0, 5).map(renderReason).join("")}</div>${offer ? renderOfferControls(selected, offer) : ""}` : `<div class="season-contract-locked">${selected.renewalLockReason || "Игрок уже продлен на будущий сезон."}</div>`}<div class="season-contract-actions">${preview ? `<button class="btn" data-action="season-contract-submit-offer" data-player-id="${selected.playerId}">Предложить контракт</button>` : ""}${preview && isOsa(selected) && decision !== "qualified" ? `<button class="btn secondary" data-action="season-contract-qualify" data-player-id="${selected.playerId}">Квалифицировать</button>` : ""}${decision === "qualified" || decision === "release" ? `<button class="btn secondary" data-action="season-contract-undo-release" data-player-id="${selected.playerId}">Вернуть в решения</button>` : ""}${preview && decision !== "qualified" && decision !== "release" ? `<button class="btn secondary danger" data-action="season-contract-release" data-player-id="${selected.playerId}">${isOsa(selected) ? "Не квалифицировать" : "Отпустить на рынок"}</button>` : ""}</div>${view.outcomesByPlayerId[selected.playerId] ? `<div class="season-contract-outcome">${view.outcomesByPlayerId[selected.playerId]}</div>` : ""}</section>` : `<section class="season-contract-detail"><div class="season-contract-empty">Нет игроков по выбранному фильтру.</div></section>`;
    return `<div class="modal season-contract-modal"><div class="season-contract-card"><div class="season-contract-header"><div><div class="season-contract-kicker">31 мая • окончание контрактов</div><h2>Решения по контрактам</h2><p>${headerText}</p></div><button class="season-contract-close" data-action="season-contract-close" aria-label="Закрыть">×</button></div><div class="season-contract-summary"><div><span>Всего</span><strong>${view.totalCount}</strong></div><div><span>Решено</span><strong>${view.resolvedCount}</strong></div><div><span>Без решения</span><strong>${view.pendingCount}</strong></div><div><span>ОСА</span><strong>${view.osaCount}</strong></div></div>${renderCapSummary(view.salaryCap)}<div class="season-contract-filters">${filterMarkup}</div><div class="season-contract-layout"><aside class="season-contract-list">${rows.map((row) => renderRow(row, view)).join("") || `<div class="season-contract-empty">Нет игроков</div>`}</aside>${detail}</div><div class="season-contract-footer">${view.osaCount ? `<button class="btn secondary" data-action="season-contract-qualify-pending-osa">Квалифицировать всех ОСА</button>` : ""}<button class="btn secondary" data-action="season-contract-release-pending">Отпустить всех без решения</button><div class="season-contract-footer-main"><span>${view.pendingCount ? `Осталось решить: ${view.pendingCount}` : "Все решения приняты"}</span><button class="btn" ${view.pendingCount ? "disabled" : ""} data-action="season-contract-confirm">Подтвердить и перейти в новый сезон</button></div></div></div></div>`;
  }
}
